[package]
name = "box_select"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bevy = "0.19"
fem_core = { path = "../fem_core" }
selection = { path = "../selection" }
camera = { path = "../camera" }
interaction = { path = "../interaction" }
