[package]
name = "bevyistr"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.19", features = ["bevy_dev_tools", "debug"] }
fem_core = { path = "../fem_core" }
hecmw = { path = "../hecmw" }
gmsh = { path = "../gmsh" }
interaction = { path = "../interaction" }
selection = { path = "../selection" }
visualization = { path = "../visualization" }
ui = { path = "../ui" }
camera = {path = "../camera"}
picking = {path = "../picking"}
box_select = {path = "../box_select"}
