//! Writer for FrontISTR analysis control files (`.cnt`).
//! Uses !ELASTIC / !DENSITY as confirmed from tutorial files.
use std::{fmt::Write as FmtWrite, io, path::Path};
use fem_core::{AnalysisSetup, AnalysisType, BoundaryCondition, DistributedLoad, DistributedLoadKind,
               DistributedLoadTarget, FemMaterial, NodalLoad, Section, SectionKind};

pub fn write_cnt_file(path: impl AsRef<Path>, setup: &AnalysisSetup)
    -> io::Result<(usize, usize, usize, usize)>
{
    std::fs::write(path, build_cnt(setup).as_bytes())?;
    let loads = setup.nodal_loads.len() + setup.distributed_loads.len();
    Ok((setup.boundary_conditions.len(), loads,
        setup.materials.len(), setup.sections.len()))
}

fn build_cnt(setup: &AnalysisSetup) -> String {
    let mut o = String::with_capacity(4096);
    writeln!(o, "!!\n!! FrontISTR Analysis Control File\n!! Generated by bevyistr\n!!").unwrap();

    // ── SOLUTION TYPE ──
    let s = &setup.solver;
    writeln!(o, "!SOLUTION, TYPE={}", s.analysis_type.frontistr_type()).unwrap();

    // ── STEP ──
    if s.analysis_type == AnalysisType::NlStatic
        || s.analysis_type == AnalysisType::Dynamic
    {
        writeln!(o, "!STEP, SUBSTEPS={}", s.substeps).unwrap();
    }

    // ── STATIC / NLSTATIC ──
    match s.analysis_type {
        AnalysisType::Static | AnalysisType::NlStatic => {
            writeln!(o, "!STATIC").unwrap();
            writeln!(o, "1, 1").unwrap();
        }
        AnalysisType::Eigen => {
            writeln!(o, "!EIGEN").unwrap();
            writeln!(o, "3").unwrap(); // default: request 3 modes
        }
        AnalysisType::Dynamic => {
            writeln!(o, "!DYNAMIC").unwrap();
        }
    }

    writeln!(o).unwrap();

    for mat in &setup.materials   { write_material(&mut o, mat); }
    for sec in &setup.sections    { write_section(&mut o, sec);  }

    // BOUNDARY — group by name
    let mut last: Option<&str> = None;
    for bc in &setup.boundary_conditions {
        if last != Some(bc.name.as_str()) {
            if last.is_some() { writeln!(o).unwrap(); }
            writeln!(o, "!BOUNDARY").unwrap();
            last = Some(&bc.name);
        }
        write_bc(&mut o, bc);
    }
    if !setup.boundary_conditions.is_empty() { writeln!(o).unwrap(); }

    // CLOAD — group by name
    let mut last: Option<&str> = None;
    for load in &setup.nodal_loads {
        if last != Some(load.name.as_str()) {
            if last.is_some() { writeln!(o).unwrap(); }
            writeln!(o, "!CLOAD").unwrap();
            last = Some(&load.name);
        }
        write_cload(&mut o, load);
    }
    if !setup.nodal_loads.is_empty() { writeln!(o).unwrap(); }

    // DLOAD
    let mut last: Option<&str> = None;
    for dl in &setup.distributed_loads {
        if last != Some(dl.name.as_str()) {
            if last.is_some() { writeln!(o).unwrap(); }
            writeln!(o, "!DLOAD").unwrap();
            last = Some(&dl.name);
        }
        write_dload(&mut o, dl);
    }
    if !setup.distributed_loads.is_empty() { writeln!(o).unwrap(); }

    // ── SOLVER ──
    writeln!(o, "!SOLVER, METHOD={}, PRECOND=1, ITERLOG=YES, TIMELOG=YES",
        s.solver_method.frontistr_method()).unwrap();
    writeln!(o, " {}, 1", s.max_iterations).unwrap();
    writeln!(o, " {:.2e}, 1.0, 0.0", s.convergence_tol).unwrap();

    writeln!(o).unwrap();
    writeln!(o, "!WRITE, RESULT").unwrap();
    writeln!(o, "!END").unwrap();

    o
}

fn write_material(o: &mut String, mat: &FemMaterial) {
    writeln!(o, "!MATERIAL, NAME={}", mat.name).unwrap();
    if mat.young_modulus.is_some() || mat.poisson_ratio.is_some() {
        writeln!(o, "!ELASTIC").unwrap();
        writeln!(o, " {}, {}, 0.0",
            mat.young_modulus.map(|v| format!("{v:.6e}")).unwrap_or_default(),
            mat.poisson_ratio.map(|v| format!("{v:.6}")).unwrap_or_default(),
        ).unwrap();
    }
    if let Some(rho) = mat.density {
        writeln!(o, "!DENSITY").unwrap();
        writeln!(o, " {rho:.6e}, 0.0").unwrap();
    }
    writeln!(o).unwrap();
}

fn write_section(o: &mut String, sec: &Section) {
    let egrp = sec.element_set_name.as_deref().unwrap_or("ALL");
    match sec.kind {
        SectionKind::Shell { thickness } => {
            writeln!(o, "!SECTION, TYPE=SHELL, EGRP={egrp}, MATERIAL={}", sec.material_name).unwrap();
            writeln!(o, " {thickness:.6e}").unwrap();
        }
        SectionKind::Beam { area } => {
            writeln!(o, "!SECTION, TYPE=BEAM, EGRP={egrp}, MATERIAL={}", sec.material_name).unwrap();
            writeln!(o, " {area:.6e}").unwrap();
        }
        SectionKind::Solid => {
            writeln!(o, "!SECTION, TYPE=SOLID, EGRP={egrp}, MATERIAL={}", sec.material_name).unwrap();
        }
    }
    writeln!(o).unwrap();
}

fn write_bc(o: &mut String, bc: &BoundaryCondition) {
    // If the original source used a NGRP name, write it back as-is
    // (e.g. "BND0, 1, 3, 0.0") rather than expanding to individual node IDs.
    // This preserves the compact FrontISTR convention and avoids bloating
    // the file when large node groups are involved.
    if let Some(ref grp) = bc.ngrp_name {
        writeln!(o, "  {},{},{},{:.6}", grp, bc.dof_start, bc.dof_end, bc.value).unwrap();
    } else {
        for node in &bc.nodes {
            writeln!(o, "  {},{},{},{:.6}", node.0, bc.dof_start, bc.dof_end, bc.value).unwrap();
        }
    }
}

fn write_cload(o: &mut String, load: &NodalLoad) {
    if let Some(ref grp) = load.ngrp_name {
        writeln!(o, "  {},{},{:.6}", grp, load.dof, load.value).unwrap();
    } else {
        writeln!(o, "  {},{},{:.6}", load.node.0, load.dof, load.value).unwrap();
    }
}
fn write_dload(o: &mut String, dl: &DistributedLoad) {
    match (dl.kind, &dl.target) {
        // Pressure: one line per element, using that element's own picked
        // local face (P1..P6) — different elements in the same named load
        // can (and often do) have the surface on a different local face,
        // so the face code can't be hoisted to a single shared value.
        (DistributedLoadKind::Pressure, DistributedLoadTarget::Faces(faces)) => {
            for face in faces {
                writeln!(o, " {},P{},{:.6}", face.element.0, face.local_face.0, dl.value).unwrap();
            }
        }
        // Pressure without face info (e.g. hand-built from a bare element
        // group rather than a picked surface) — fall back to local face 1
        // rather than emitting FrontISTR's invalid/nonexistent "P0".
        (DistributedLoadKind::Pressure, DistributedLoadTarget::Elements(elements)) => {
            for el in elements {
                writeln!(o, " {},P1,{:.6}", el.0, dl.value).unwrap();
            }
        }
        (DistributedLoadKind::Gravity, target) => {
            for el in target.element_ids() {
                writeln!(o, " {},GRAV,{:.6}", el.0, dl.value).unwrap();
            }
        }
    }
}
