//! Writer for FrontISTR analysis control files (`.cnt`).
//! Uses !ELASTIC / !DENSITY as confirmed from tutorial files.
use fem_core::{
    AnalysisSetup, AnalysisType, BoundaryCondition, ContactPair, ContactType, DistributedLoad,
    DistributedLoadKind, DistributedLoadTarget, FemMaterial, NodalLoad, RotationCenter,
};
use std::{collections::HashSet, fmt::Write as FmtWrite, io, path::Path};

pub fn write_cnt_file(
    path: impl AsRef<Path>,
    setup: &AnalysisSetup,
) -> io::Result<(usize, usize, usize, usize)> {
    let (boundary_conditions, loads, materials, sections, _) =
        write_cnt_file_with_contacts(path, setup, &[])?;

    Ok((boundary_conditions, loads, materials, sections))
}

/// Writes a FrontISTR analysis control file including accepted contact
/// interactions. Contact geometry itself is emitted by the mesh writer as
/// `!CONTACT PAIR`; this writer references those pair names from `!CONTACT`.
pub fn write_cnt_file_with_contacts(
    path: impl AsRef<Path>,
    setup: &AnalysisSetup,
    contacts: &[ContactPair],
) -> io::Result<(usize, usize, usize, usize, usize)> {
    std::fs::write(path, build_cnt(setup, contacts).as_bytes())?;
    let loads = setup.nodal_loads.len() + setup.distributed_loads.len();
    Ok((
        setup.boundary_conditions.len(),
        loads,
        setup.materials.len(),
        setup.sections.len(),
        contacts.len(),
    ))
}

fn build_cnt(setup: &AnalysisSetup, contacts: &[ContactPair]) -> String {
    let mut o = String::with_capacity(4096);
    writeln!(
        o,
        "!!\n!! FrontISTR Analysis Control File\n!! Generated by bevyistr\n!!"
    )
    .unwrap();
    writeln!(o, "!VERSION\n 3").unwrap();

    // ── SOLUTION TYPE ──
    let s = &setup.solver;
    if s.analysis_type == AnalysisType::NlStatic {
        writeln!(o, "!SOLUTION, TYPE=STATIC, NONLINEAR").unwrap();
    } else {
        writeln!(o, "!SOLUTION, TYPE={}", s.analysis_type.frontistr_type()).unwrap();
    }

    // ── STEP ──
    if s.analysis_type == AnalysisType::NlStatic || s.analysis_type == AnalysisType::Dynamic {
        writeln!(o, "!STEP, SUBSTEPS={}", s.substeps).unwrap();
        if !setup.boundary_conditions.is_empty() {
            writeln!(o, "BOUNDARY, 1").unwrap();
        }
        if !setup.nodal_loads.is_empty() || !setup.distributed_loads.is_empty() {
            writeln!(o, "LOAD, 1").unwrap();
        }
        for group_id in 1..=contacts.len() {
            writeln!(o, "CONTACT, {group_id}").unwrap();
        }
    }

    // ── STATIC / NLSTATIC ──
    match s.analysis_type {
        AnalysisType::Static | AnalysisType::NlStatic => {
            writeln!(o, "!STATIC").unwrap();
            writeln!(o, "1, 1").unwrap();
        }
        AnalysisType::Eigen => {
            writeln!(o, "!EIGEN").unwrap();
            writeln!(o, "3").unwrap(); // default: request 3 modes
        }
        AnalysisType::Dynamic => {
            writeln!(o, "!DYNAMIC").unwrap();
        }
    }

    writeln!(o).unwrap();

    for mat in &setup.materials {
        write_material(&mut o, mat);
    }

    // BOUNDARY — group by name
    let mut last: Option<(&str, Option<&RotationCenter>)> = None;
    for bc in &setup.boundary_conditions {
        let key = (bc.name.as_str(), bc.rotation_center.as_ref());
        if last != Some(key) {
            if last.is_some() {
                writeln!(o).unwrap();
            }
            write_condition_header(&mut o, "BOUNDARY", bc.rotation_center.as_ref());
            last = Some(key);
        }
        write_bc(&mut o, bc);
    }
    if !setup.boundary_conditions.is_empty() {
        writeln!(o).unwrap();
    }

    // CLOAD — group by name
    let mut last: Option<(&str, Option<&RotationCenter>)> = None;
    let mut written_compact_loads = HashSet::new();
    for load in &setup.nodal_loads {
        if let Some(group) = &load.ngrp_name {
            let compact_key = (
                load.name.clone(),
                group.clone(),
                load.dof,
                load.value.to_bits(),
                load.rotation_center.clone(),
            );
            if !written_compact_loads.insert(compact_key) {
                continue;
            }
        }
        let key = (load.name.as_str(), load.rotation_center.as_ref());
        if last != Some(key) {
            if last.is_some() {
                writeln!(o).unwrap();
            }
            write_condition_header(&mut o, "CLOAD", load.rotation_center.as_ref());
            last = Some(key);
        }
        write_cload(&mut o, load);
    }
    if !setup.nodal_loads.is_empty() {
        writeln!(o).unwrap();
    }

    // DLOAD
    let mut last: Option<&str> = None;
    for dl in &setup.distributed_loads {
        if last != Some(dl.name.as_str()) {
            if last.is_some() {
                writeln!(o).unwrap();
            }
            writeln!(o, "!DLOAD, GRPID=1").unwrap();
            last = Some(&dl.name);
        }
        write_dload(&mut o, dl);
    }
    if !setup.distributed_loads.is_empty() {
        writeln!(o).unwrap();
    }

    // CONTACT — one boundary-condition group per accepted pair. Keeping
    // pairs separate allows interaction parameters to diverge later without
    // changing the file layout or the step activation model.
    for (index, contact) in contacts.iter().enumerate() {
        write_contact(&mut o, contact, index + 1);
    }

    // ── SOLVER ──
    writeln!(
        o,
        "!SOLVER, METHOD={}, PRECOND=1, ITERLOG=YES, TIMELOG=YES",
        s.solver_method.frontistr_method()
    )
    .unwrap();
    writeln!(o, " {}, 1", s.max_iterations).unwrap();
    writeln!(o, " {:.2e}, 1.0, 0.0", s.convergence_tol).unwrap();

    writeln!(o).unwrap();
    writeln!(o, "!WRITE, RESULT").unwrap();
    writeln!(o, "!WRITE, VISUAL").unwrap();
    writeln!(o, "!VISUAL, METHOD=PSR").unwrap();
    writeln!(o, "!surface_num=1").unwrap();
    writeln!(o, "!surface 1").unwrap();
    writeln!(o, "!output_type=VTK").unwrap();
    writeln!(o, "!END").unwrap();

    o
}

fn write_condition_header(out: &mut String, keyword: &str, center: Option<&RotationCenter>) {
    write!(out, "!{keyword}, GRPID=1").unwrap();
    if let Some(token) = center.and_then(rotation_center_token) {
        write!(out, ", ROT_CENTER={token}").unwrap();
    }
    writeln!(out).unwrap();
}

fn rotation_center_token(center: &RotationCenter) -> Option<String> {
    center
        .ngrp_name
        .clone()
        .or_else(|| center.node.map(|node| node.0.to_string()))
}

fn write_contact(out: &mut String, contact: &ContactPair, group_id: usize) {
    writeln!(
        out,
        "!CONTACT, GRPID={group_id}, INTERACTION={}",
        contact.contact_type.frontistr_interaction()
    )
    .unwrap();
    match contact.contact_type {
        ContactType::Tied => writeln!(out, " {}", contact.name).unwrap(),
        ContactType::SmallSliding | ContactType::FiniteSliding => {
            if let Some(factor) = contact.penalty_factor {
                writeln!(
                    out,
                    " {},{:.6e},{factor:.6e}",
                    contact.name, contact.friction_coefficient
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    " {},{:.6e}",
                    contact.name, contact.friction_coefficient
                )
                .unwrap();
            }
        }
    }
    writeln!(out).unwrap();
}

fn write_material(o: &mut String, mat: &FemMaterial) {
    writeln!(o, "!MATERIAL, NAME={}", mat.name).unwrap();
    if mat.young_modulus.is_some() || mat.poisson_ratio.is_some() {
        writeln!(o, "!ELASTIC").unwrap();
        writeln!(
            o,
            " {}, {}, 0.0",
            mat.young_modulus
                .map(|v| format!("{v:.6e}"))
                .unwrap_or_default(),
            mat.poisson_ratio
                .map(|v| format!("{v:.6}"))
                .unwrap_or_default(),
        )
        .unwrap();
    }
    if let Some(rho) = mat.density {
        writeln!(o, "!DENSITY").unwrap();
        writeln!(o, " {rho:.6e}, 0.0").unwrap();
    }
    writeln!(o).unwrap();
}

fn write_bc(o: &mut String, bc: &BoundaryCondition) {
    // If the original source used a NGRP name, write it back as-is
    // (e.g. "BND0, 1, 3, 0.0") rather than expanding to individual node IDs.
    // This preserves the compact FrontISTR convention and avoids bloating
    // the file when large node groups are involved.
    if let Some(ref grp) = bc.ngrp_name {
        writeln!(
            o,
            "  {},{},{},{:.6}",
            grp, bc.dof_start, bc.dof_end, bc.value
        )
        .unwrap();
    } else {
        for node in &bc.nodes {
            writeln!(
                o,
                "  {},{},{},{:.6}",
                node.0, bc.dof_start, bc.dof_end, bc.value
            )
            .unwrap();
        }
    }
}

fn write_cload(o: &mut String, load: &NodalLoad) {
    if let Some(ref grp) = load.ngrp_name {
        writeln!(o, "  {},{},{:.6}", grp, load.dof, load.value).unwrap();
    } else {
        writeln!(o, "  {},{},{:.6}", load.node.0, load.dof, load.value).unwrap();
    }
}
fn write_dload(o: &mut String, dl: &DistributedLoad) {
    match (dl.kind, &dl.target) {
        // Pressure: one line per element, using that element's own picked
        // local face (P1..P6) — different elements in the same named load
        // can (and often do) have the surface on a different local face,
        // so the face code can't be hoisted to a single shared value.
        (DistributedLoadKind::Pressure, DistributedLoadTarget::Faces(faces)) => {
            for face in faces {
                writeln!(
                    o,
                    " {},P{},{:.6}",
                    face.element.0, face.local_face.0, dl.value
                )
                .unwrap();
            }
        }
        // Pressure without face info (e.g. hand-built from a bare element
        // group rather than a picked surface) — fall back to local face 1
        // rather than emitting FrontISTR's invalid/nonexistent "P0".
        (DistributedLoadKind::Pressure, DistributedLoadTarget::Elements(elements)) => {
            for el in elements {
                writeln!(o, " {},P1,{:.6}", el.0, dl.value).unwrap();
            }
        }
        (DistributedLoadKind::Gravity, target) => {
            let direction = dl
                .direction
                .filter(|direction| direction.length_squared() > f32::EPSILON)
                .map(|direction| direction.normalize())
                .unwrap_or(bevy::prelude::Vec3::NEG_Y);
            for el in target.element_ids() {
                writeln!(
                    o,
                    " {},GRAV,{:.6},{:.6},{:.6},{:.6}",
                    el.0, dl.value, direction.x, direction.y, direction.z,
                )
                .unwrap();
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use bevy::prelude::Vec3;
    use fem_core::{
        BoundaryCondition, ContactPair, ContactType, DistributedLoad, DistributedLoadKind,
        DistributedLoadTarget, ElementId, LinearSolverMethod, NodalLoad, NodeId, SurfaceSetRef,
    };

    use super::*;

    #[test]
    fn preserves_mumps_as_the_frontistr_solver_method() {
        let mut setup = AnalysisSetup::default();
        setup.solver.solver_method = LinearSolverMethod::Mumps;

        let text = build_cnt(&setup, &[]);

        assert!(text.contains("!SOLVER, METHOD=MUMPS,"));
        assert!(!text.contains("METHOD=DIRECT"));
    }

    #[test]
    fn writes_tied_and_sliding_contact_interactions() {
        let contacts = vec![
            ContactPair::new(
                "TIED_PAIR",
                SurfaceSetRef::new(0, 0),
                SurfaceSetRef::new(0, 1),
                ContactType::Tied,
            ),
            ContactPair::new(
                "SMALL_SLIDING_PAIR",
                SurfaceSetRef::new(0, 2),
                SurfaceSetRef::new(0, 3),
                ContactType::SmallSliding,
            ),
            ContactPair::new(
                "FINITE_SLIDING_PAIR",
                SurfaceSetRef::new(0, 4),
                SurfaceSetRef::new(0, 5),
                ContactType::FiniteSliding,
            )
            .with_contact_parameters(0.1, Some(1.0e5)),
        ];

        let text = build_cnt(&AnalysisSetup::default(), &contacts);

        assert!(text.contains("!CONTACT, GRPID=1, INTERACTION=TIED\n TIED_PAIR\n"));
        assert!(
            text.contains("!CONTACT, GRPID=2, INTERACTION=SSLID\n SMALL_SLIDING_PAIR,0.000000e0\n")
        );
        assert!(text.contains(
            "!CONTACT, GRPID=3, INTERACTION=FSLID\n FINITE_SLIDING_PAIR,1.000000e-1,1.000000e5\n"
        ));
    }

    #[test]
    fn activates_each_contact_group_in_nonlinear_step() {
        let mut setup = AnalysisSetup::default();
        setup.solver.analysis_type = AnalysisType::NlStatic;
        let contacts = vec![ContactPair::new(
            "PAIR",
            SurfaceSetRef::new(0, 0),
            SurfaceSetRef::new(0, 1),
            ContactType::Tied,
        )];

        let text = build_cnt(&setup, &contacts);

        assert!(text.contains("!SOLUTION, TYPE=STATIC, NONLINEAR\n"));
        assert!(text.contains("!STEP, SUBSTEPS=1\nCONTACT, 1\n"));
    }

    #[test]
    fn writes_vtk_visualization_controls() {
        let text = build_cnt(&AnalysisSetup::default(), &[]);

        assert!(text.contains("!WRITE, VISUAL\n"));
        assert!(
            text.contains("!VISUAL, METHOD=PSR\n!surface_num=1\n!surface 1\n!output_type=VTK\n")
        );
    }

    #[test]
    fn writes_all_required_gravity_parameters() {
        let mut setup = AnalysisSetup::default();
        setup.distributed_loads.push(DistributedLoad {
            name: "GRAVITY".into(),
            mesh_index: 0,
            target: DistributedLoadTarget::Elements(vec![ElementId(7)]),
            kind: DistributedLoadKind::Gravity,
            value: 9.81,
            direction: Some(Vec3::new(0.0, 0.0, -2.0)),
        });

        let text = build_cnt(&setup, &[]);

        assert!(text.contains("!DLOAD, GRPID=1\n 7,GRAV,9.810000,0.000000,0.000000,-1.000000\n"));
    }

    #[test]
    fn writes_exact_prescribed_rotation_and_nodal_moment() {
        let mut setup = AnalysisSetup::default();
        setup.boundary_conditions.push(BoundaryCondition {
            name: "BC_EXACT".into(),
            mesh_index: 0,
            nodes: vec![NodeId(42)],
            ngrp_name: None,
            rotation_center: None,
            dof_start: 4,
            dof_end: 4,
            value: 0.125,
        });
        setup.nodal_loads.push(NodalLoad {
            name: "MOMENT_EXACT".into(),
            mesh_index: 0,
            node: NodeId(42),
            ngrp_name: None,
            rotation_center: None,
            dof: 6,
            value: -12.5,
        });

        let text = build_cnt(&setup, &[]);

        assert!(text.contains("!BOUNDARY, GRPID=1\n  42,4,4,0.125000\n"));
        assert!(text.contains("!CLOAD, GRPID=1\n  42,6,-12.500000\n"));
    }

    #[test]
    fn writes_rot_center_headers_without_conflating_direct_rotations() {
        let center = RotationCenter::from_node(0, NodeId(7));
        let mut setup = AnalysisSetup::default();
        setup.boundary_conditions.push(BoundaryCondition {
            name: "BC_ROT_CENTER".into(),
            mesh_index: 0,
            nodes: vec![NodeId(42)],
            ngrp_name: None,
            rotation_center: Some(center.clone()),
            dof_start: 1,
            dof_end: 1,
            value: 0.125,
        });
        setup.nodal_loads.push(NodalLoad {
            name: "TORQUE_CENTER".into(),
            mesh_index: 0,
            node: NodeId(42),
            ngrp_name: None,
            rotation_center: Some(center),
            dof: 3,
            value: -12.5,
        });

        let text = build_cnt(&setup, &[]);

        assert!(text.contains("!BOUNDARY, GRPID=1, ROT_CENTER=7\n  42,1,1,0.125000\n"));
        assert!(text.contains("!CLOAD, GRPID=1, ROT_CENTER=7\n  42,3,-12.500000\n"));
    }

    #[test]
    fn writes_a_compact_cload_group_only_once_after_parser_expansion() {
        let mut setup = AnalysisSetup::default();
        for node in [NodeId(1), NodeId(2)] {
            setup.nodal_loads.push(NodalLoad {
                name: "GROUP_LOAD".into(),
                mesh_index: 0,
                node,
                ngrp_name: Some("LOADED_NODES".into()),
                rotation_center: None,
                dof: 1,
                value: 25.0,
            });
        }

        let text = build_cnt(&setup, &[]);

        assert_eq!(text.matches("  LOADED_NODES,1,25.000000\n").count(), 1);
    }
}
