use std::{fmt::Write as FmtWrite, io, path::Path};

pub struct HecmwCtrlParams<'a> {
    pub mesh_name:   &'a str,
    pub cnt_name:    &'a str,
    pub result_name: &'a str,
}

pub fn write_hecmw_ctrl(dir: impl AsRef<Path>, p: &HecmwCtrlParams<'_>) -> io::Result<()> {
    let path = dir.as_ref().join("hecmw_ctrl.dat");
    let mut out = String::new();
    writeln!(out, "#\n# Generated by bevyistr\n#").unwrap();
    writeln!(out, "!MESH, NAME=fstrMSH, TYPE=HECMW-ENTIRE\n {}.msh", p.mesh_name).unwrap();
    writeln!(out, "!CONTROL, NAME=fstrCNT\n {}.cnt", p.cnt_name).unwrap();
    writeln!(out, "!RESULT, NAME=fstrRES, IO=OUT\n {}.res", p.result_name).unwrap();
    writeln!(out, "!RESULT, NAME=vis_out, IO=OUT\n {}_vis", p.result_name).unwrap();
    std::fs::write(path, out.as_bytes())
}
