use std::{fmt::Write as FmtWrite, io, path::Path};

pub struct HecmwCtrlParams<'a> {
    pub mesh_name: &'a str,
    pub cnt_name: &'a str,
    pub result_name: &'a str,
}

pub fn write_hecmw_ctrl(dir: impl AsRef<Path>, p: &HecmwCtrlParams<'_>) -> io::Result<()> {
    let path = dir.as_ref().join("hecmw_ctrl.dat");
    let mut out = String::new();
    writeln!(out, "#\n# Generated by bevyistr\n#").unwrap();
    writeln!(
        out,
        "!MESH, NAME=fstrMSH, TYPE=HECMW-ENTIRE\n {}.msh",
        p.mesh_name
    )
    .unwrap();
    writeln!(out, "!CONTROL, NAME=fstrCNT\n {}.cnt", p.cnt_name).unwrap();
    writeln!(out, "!RESULT, NAME=fstrRES, IO=OUT\n {}.res", p.result_name).unwrap();
    writeln!(out, "!RESULT, NAME=vis_out, IO=OUT\n {}_vis", p.result_name).unwrap();
    std::fs::write(path, out.as_bytes())
}

/// Controls for the official two-stage MPI workflow: partition the entire
/// mesh, then solve the distributed mesh. The caller owns `distributed_name`
/// and must not reuse stale partition files.
pub fn write_parallel_hecmw_ctrl(
    dir: impl AsRef<Path>,
    p: &HecmwCtrlParams<'_>,
    distributed_name: &str,
    ranks: u16,
) -> io::Result<()> {
    if ranks == 0
        || [p.mesh_name, p.cnt_name, p.result_name, distributed_name]
            .iter()
            .any(|name| {
                name.is_empty()
                    || name.contains(['\r', '\n', '/', '\\'])
                    || matches!(*name, "." | "..")
            })
    {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "Invalid parallel project name or domain count",
        ));
    }
    let mut out = String::from("# Generated by bevyistr: partition first, then solve\n");
    writeln!(
        out,
        "!MESH, NAME=part_in, TYPE=HECMW-ENTIRE\n {}.msh",
        p.mesh_name
    )
    .unwrap();
    writeln!(
        out,
        "!MESH, NAME=part_out, TYPE=HECMW-DIST\n {distributed_name}"
    )
    .unwrap();
    writeln!(
        out,
        "!MESH, NAME=fstrMSH, TYPE=HECMW-DIST\n {distributed_name}"
    )
    .unwrap();
    writeln!(out, "!CONTROL, NAME=fstrCNT\n {}.cnt", p.cnt_name).unwrap();
    writeln!(out, "!RESULT, NAME=fstrRES, IO=OUT\n {}.res", p.result_name).unwrap();
    writeln!(out, "!RESULT, NAME=vis_out, IO=OUT\n {}_vis", p.result_name).unwrap();
    std::fs::write(
        dir.as_ref().join("hecmw_part_ctrl.dat"),
        format!("!PARTITION, TYPE=NODE-BASED, METHOD=PMETIS, DOMAIN={ranks}\n"),
    )?;
    std::fs::write(dir.as_ref().join("hecmw_ctrl.dat"), out)
}
