//! Writer for the HECMW mesh file format (`.msh`).
//!
//! The HECMW `.msh` format is what FrontISTR expects as its mesh input,
//! specified in `hecmw_ctrl.dat`. This writer produces the subset of keywords
//! that every non-trivial FrontISTR analysis needs:
//!
//!   `!HEADER`, `!NODE`, `!ELEMENT` (one block per element type),
//!   `!NGROUP`, `!EGROUP`, `!SGROUP`, `!CONTACT PAIR`, `!END`
//!
//! Coordinates are written in full `f64`-formatted `f32` values (6 decimal
//! places) so precision is not lost in a read-modify-write round-trip even
//! though `FemNode::position` is `Vec3` (f32).
//!
//! # Multi-part assembly export
//!
//! HECMW's `.msh` format has no native concept of "multiple meshes in one
//! file" the way an assembly might — everything is one flat
//! node/element/group space. So when a [`FemModel`] has more than one part
//! (built via "+ Import"), [`write_msh_file`] flattens them into a single
//! mesh by re-numbering every part's node and element IDs into disjoint
//! ranges (offsetting by the running totals of all earlier parts) and
//! prefixing every group name with the part name (`PART2_EGRP1`) so that
//! identically-named groups from different source files don't collide.
//! Contact surface pairs are mesh definitions in FrontISTR, so accepted
//! contacts are exported as `TYPE=SURF-SURF` pairs after their surface
//! groups. Their interaction law is written to the analysis `.cnt` file.

use std::fmt::Write as FmtWrite;
use std::io;
use std::path::Path;

use fem_core::{ElementId, ElementType, FemMesh, FemModel, NodeId, SurfaceSetRef};

#[derive(Debug, Clone, PartialEq, Eq)]
struct ExportContactPair {
    name: String,
    slave_group: String,
    master_group: String,
}

// ─── public API ──────────────────────────────────────────────────────────────

/// Writes the first mesh of `model` to `path` in HECMW `.msh` format.
///
/// Returns the number of nodes and elements written on success, for the
/// caller to surface in the status bar.
///
/// For models with a single mesh, this is equivalent to (and a thin
/// wrapper over) [`write_msh_assembly`] — kept as a separate name because
/// "write the mesh" reads more naturally than "write the assembly" for the
/// overwhelmingly common single-part case, and existing callers don't need
/// to change.
pub fn write_msh_file(
    path: impl AsRef<Path>,
    model: &FemModel,
    mesh_index: usize,
) -> io::Result<(usize, usize)> {
    let mesh = model.meshes.get(mesh_index).ok_or_else(|| {
        io::Error::new(io::ErrorKind::InvalidInput, "mesh index out of range")
    })?;

    let contacts = resolve_contact_pairs(model, Some(mesh_index), false)?;
    let text = build_msh(mesh, &contacts);
    std::fs::write(path, text.as_bytes())?;

    Ok((mesh.nodes.len(), mesh.elements.len()))
}

/// Writes **every** mesh in `model` to `path` as one flattened HECMW
/// `.msh`, renumbering node/element IDs into disjoint ranges and prefixing
/// group names by part so multi-part assemblies (built via "+ Import")
/// export correctly instead of silently dropping every part after the
/// first.
///
/// Returns `(total_nodes, total_elements, part_count)`.
pub fn write_msh_assembly(
    path: impl AsRef<Path>,
    model: &FemModel,
) -> io::Result<(usize, usize, usize)> {
    if model.meshes.len() <= 1 {
        // Single-part fast path — no renumbering or prefixing needed.
        let (n, e) = write_msh_file(&path, model, 0)?;
        return Ok((n, e, model.meshes.len()));
    }

    let mut combined = String::with_capacity(1024 * 64 * model.meshes.len());
    writeln!(combined, "!HEADER").unwrap();
    writeln!(combined, " Generated by bevyistr (assembly, {} parts)", model.meshes.len()).unwrap();

    // First pass: compute per-part ID offsets so every part's node/element
    // IDs land in a disjoint range in the combined file.
    let mut node_offset: u32 = 0;
    let mut elem_offset: u32 = 0;
    let mut offsets: Vec<(u32, u32)> = Vec::with_capacity(model.meshes.len());
    for mesh in &model.meshes {
        offsets.push((node_offset, elem_offset));
        node_offset += mesh.nodes.iter().map(|n| n.id.0).max().unwrap_or(0) + 1;
        elem_offset += mesh.elements.iter().map(|e| e.id.0).max().unwrap_or(0) + 1;
    }

    // ── NODE (all parts) ──
    writeln!(combined, "!NODE").unwrap();
    for (mesh, &(noff, _)) in model.meshes.iter().zip(&offsets) {
        for node in &mesh.nodes {
            writeln!(
                combined, " {},{:.6},{:.6},{:.6}",
                node.id.0 + noff, node.position.x, node.position.y, node.position.z,
            ).unwrap();
        }
    }

    // ── ELEMENT (all parts, grouped by type across all parts) ──
    let mut type_codes_seen: Vec<&str> = Vec::new();
    for mesh in &model.meshes {
        for el in &mesh.elements {
            if let Some(code) = element_type_code(&el.element_type) {
                if !type_codes_seen.contains(&code) { type_codes_seen.push(code); }
            }
        }
    }
    for code in &type_codes_seen {
        writeln!(combined, "!ELEMENT,TYPE={code}").unwrap();
        for (mesh, &(noff, eoff)) in model.meshes.iter().zip(&offsets) {
            for el in mesh.elements.iter().filter(|e| element_type_code(&e.element_type) == Some(code)) {
                let node_list: Vec<String> = el.nodes.iter().map(|n| (n.0 + noff).to_string()).collect();
                writeln!(combined, " {},{}", el.id.0 + eoff, node_list.join(",")).unwrap();
            }
        }
    }

    // ── NGROUP / EGROUP / SGROUP (prefixed by part name to avoid collisions) ──
    for (part_index, (mesh, &(noff, eoff))) in model.meshes.iter().zip(&offsets).enumerate() {
        let part_name = part_group_prefix(model, part_index);

        for nset in &mesh.node_sets {
            writeln!(combined, "!NGROUP,NGRP={part_name}_{}", nset.name).unwrap();
            write_id_list(&mut combined, nset.nodes.iter().map(|n| n.0 + noff));
        }
        for eset in &mesh.element_sets {
            writeln!(combined, "!EGROUP,EGRP={part_name}_{}", eset.name).unwrap();
            write_id_list(&mut combined, eset.elements.iter().map(|e| e.0 + eoff));
        }
        for sset in &mesh.surface_sets {
            writeln!(combined, "!SGROUP,SGRP={part_name}_{}", sset.name).unwrap();
            for surf in &sset.surfaces {
                writeln!(combined, " {},{}", surf.element.0 + eoff, surf.local_face.0).unwrap();
            }
        }
    }

    write_contact_pairs(
        &mut combined,
        &resolve_contact_pairs(model, None, true)?,
    );

    writeln!(combined, "!END").unwrap();
    std::fs::write(path, combined.as_bytes())?;

    let total_nodes:    usize = model.meshes.iter().map(|m| m.nodes.len()).sum();
    let total_elements: usize = model.meshes.iter().map(|m| m.elements.len()).sum();

    Ok((total_nodes, total_elements, model.meshes.len()))
}

/// Builds the global node/element ID remap a multi-part export would use,
/// without writing anything — exposed mainly for tests and for the `.cnt`
/// writer, which needs the *same* offsets to remap boundary
/// conditions/loads/sections that reference node or element IDs from a
/// specific part's original numbering.
pub fn assembly_id_offsets(model: &FemModel) -> Vec<(u32, u32)> {
    let mut node_offset: u32 = 0;
    let mut elem_offset: u32 = 0;
    let mut offsets = Vec::with_capacity(model.meshes.len());
    for mesh in &model.meshes {
        offsets.push((node_offset, elem_offset));
        node_offset += mesh.nodes.iter().map(|n| n.id.0).max().unwrap_or(0) + 1;
        elem_offset += mesh.elements.iter().map(|e| e.id.0).max().unwrap_or(0) + 1;
    }
    offsets
}

/// Remaps a `(mesh_index, NodeId)` pair to its assembly-wide [`NodeId`]
/// using the offsets from [`assembly_id_offsets`].
pub fn remap_node(offsets: &[(u32, u32)], mesh_index: usize, id: NodeId) -> NodeId {
    let (noff, _) = offsets.get(mesh_index).copied().unwrap_or((0, 0));
    NodeId(id.0 + noff)
}

/// Remaps a `(mesh_index, ElementId)` pair to its assembly-wide
/// [`ElementId`] using the offsets from [`assembly_id_offsets`].
pub fn remap_element(offsets: &[(u32, u32)], mesh_index: usize, id: ElementId) -> ElementId {
    let (_, eoff) = offsets.get(mesh_index).copied().unwrap_or((0, 0));
    ElementId(id.0 + eoff)
}

// ─── implementation ──────────────────────────────────────────────────────────

/// Strips characters that would be ambiguous or illegal in a HECMW group
/// name (commas, whitespace) from a part's display name when using it as a
/// group-name prefix.
fn sanitize_group_prefix(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect::<String>()
        .trim_end_matches(".msh")
        .to_string()
        .to_ascii_uppercase()
}

fn part_group_prefix(model: &FemModel, mesh_index: usize) -> String {
    model
        .parts
        .iter()
        .find(|part| part.mesh_index == mesh_index)
        .map(|part| sanitize_group_prefix(&part.name))
        .unwrap_or_else(|| format!("PART{}", mesh_index + 1))
}

fn exported_surface_group_name(
    model: &FemModel,
    surface: SurfaceSetRef,
    prefix_part: bool,
) -> io::Result<String> {
    let mesh = model.meshes.get(surface.mesh_index).ok_or_else(|| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("contact references missing mesh {}", surface.mesh_index),
        )
    })?;
    let surface_set = mesh
        .surface_sets
        .get(surface.surface_set_index)
        .ok_or_else(|| {
            io::Error::new(
                io::ErrorKind::InvalidData,
                format!(
                    "contact references missing surface set {} on mesh {}",
                    surface.surface_set_index, surface.mesh_index
                ),
            )
        })?;

    if prefix_part {
        Ok(format!(
            "{}_{}",
            part_group_prefix(model, surface.mesh_index),
            surface_set.name
        ))
    } else {
        Ok(surface_set.name.clone())
    }
}

fn resolve_contact_pairs(
    model: &FemModel,
    selected_mesh: Option<usize>,
    prefix_parts: bool,
) -> io::Result<Vec<ExportContactPair>> {
    let mut resolved = Vec::with_capacity(model.contacts.len());

    for contact in &model.contacts {
        if let Some(mesh_index) = selected_mesh {
            let master_selected = contact.master.mesh_index == mesh_index;
            let slave_selected = contact.slave.mesh_index == mesh_index;

            if !master_selected && !slave_selected {
                continue;
            }

            if master_selected != slave_selected {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    format!(
                        "contact '{}' crosses mesh boundaries; export the assembly instead",
                        contact.name
                    ),
                ));
            }
        }

        resolved.push(ExportContactPair {
            name: contact.name.clone(),
            slave_group: exported_surface_group_name(model, contact.slave, prefix_parts)?,
            master_group: exported_surface_group_name(model, contact.master, prefix_parts)?,
        });
    }

    Ok(resolved)
}

fn write_contact_pairs(out: &mut String, contacts: &[ExportContactPair]) {
    for contact in contacts {
        writeln!(
            out,
            "!CONTACT PAIR, NAME={}, TYPE=SURF-SURF",
            contact.name
        )
        .unwrap();
        writeln!(out, " {},{}", contact.slave_group, contact.master_group).unwrap();
    }
}

fn write_id_list(out: &mut String, ids: impl Iterator<Item = u32>) {
    let mut col = 0;
    let ids: Vec<u32> = ids.collect();
    for (i, id) in ids.iter().enumerate() {
        if col == 0 {
            write!(out, " {id}").unwrap();
        } else {
            write!(out, ",{id}").unwrap();
        }
        col += 1;
        if col == 10 || i + 1 == ids.len() {
            writeln!(out).unwrap();
            col = 0;
        }
    }
}

fn element_type_code(et: &ElementType) -> Option<&'static str> {
    match et {
        ElementType::Rod2    => Some("111"),
        ElementType::Rod3    => Some("112"),
        ElementType::Tri3    => Some("231"),
        ElementType::Tri6    => Some("232"),
        ElementType::Quad4   => Some("241"),
        ElementType::Quad8   => Some("242"),
        ElementType::Truss2  => Some("301"),
        ElementType::Tet4    => Some("341"),
        ElementType::Tet10   => Some("342"),
        ElementType::Prism6  => Some("351"),
        ElementType::Prism15 => Some("352"),
        ElementType::Hex8    => Some("361"),
        ElementType::Hex20   => Some("362"),
        ElementType::Connector2 => Some("511"),
        ElementType::InterfaceQuad4 => Some("541"),
        ElementType::InterfaceQuad8 => Some("542"),
        ElementType::Beam611 => Some("611"),
        ElementType::Beam641 => Some("641"),
        ElementType::ShellTri3 => Some("731"),
        ElementType::ShellTri6 => Some("732"),
        ElementType::ShellQuad4 => Some("741"),
        ElementType::ShellQuad9 => Some("743"),
        ElementType::ShellTri3Mixed => Some("761"),
        ElementType::ShellQuad4Mixed => Some("781"),
        ElementType::Unsupported(_) => None,
    }
}

fn build_msh(mesh: &FemMesh, contacts: &[ExportContactPair]) -> String {
    let mut out = String::with_capacity(1024 * 64);

    // ── HEADER ──
    writeln!(out, "!HEADER").unwrap();
    writeln!(out, " Generated by bevyistr").unwrap();

    // ── NODE ──
    writeln!(out, "!NODE").unwrap();
    for node in &mesh.nodes {
        writeln!(
            out,
            " {},{:.6},{:.6},{:.6}",
            node.id.0,
            node.position.x,
            node.position.y,
            node.position.z,
        ).unwrap();
    }

    // ── ELEMENT — one !ELEMENT block per unique element type ──
    let mut type_codes_seen: Vec<&str> = Vec::new();
    for el in &mesh.elements {
        if let Some(code) = element_type_code(&el.element_type) {
            if !type_codes_seen.contains(&code) {
                type_codes_seen.push(code);
            }
        }
    }

    for code in &type_codes_seen {
        writeln!(out, "!ELEMENT,TYPE={code}").unwrap();

        for el in mesh.elements.iter().filter(|e| element_type_code(&e.element_type) == Some(code)) {
            let node_list: Vec<String> = el.nodes.iter().map(|n| n.0.to_string()).collect();
            writeln!(out, " {},{}", el.id.0, node_list.join(",")).unwrap();
        }
    }

    // ── NGROUP ──
    for nset in &mesh.node_sets {
        writeln!(out, "!NGROUP,NGRP={}", nset.name).unwrap();
        write_id_list(&mut out, nset.nodes.iter().map(|n| n.0));
    }

    // ── EGROUP ──
    for eset in &mesh.element_sets {
        writeln!(out, "!EGROUP,EGRP={}", eset.name).unwrap();
        write_id_list(&mut out, eset.elements.iter().map(|e| e.0));
    }

    // ── SGROUP (surface groups) ──
    for sset in &mesh.surface_sets {
        writeln!(out, "!SGROUP,SGRP={}", sset.name).unwrap();
        for surf in &sset.surfaces {
            writeln!(out, " {},{}", surf.element.0, surf.local_face.0).unwrap();
        }
    }

    write_contact_pairs(&mut out, contacts);

    writeln!(out, "!END").unwrap();

    out
}

#[cfg(test)]
mod tests {
    use fem_core::{
        ContactPair, ContactType, ElementFaceRef, ElementId, FemMesh, FemSurfaceSet, LocalFaceId,
        SurfaceSetRef,
    };

    use super::*;

    fn add_surface(mesh: &mut FemMesh, name: &str, local_face: u32) {
        mesh.surface_sets.push(FemSurfaceSet {
            name: name.into(),
            surfaces: vec![ElementFaceRef::new(
                ElementId(0),
                LocalFaceId(local_face),
            )],
        });
    }

    #[test]
    fn writes_surface_to_surface_contact_pair_in_slave_master_order() {
        let mut model = FemModel::demo_hex8();
        add_surface(&mut model.meshes[0], "MASTER", 1);
        add_surface(&mut model.meshes[0], "SLAVE", 2);
        model.contacts.push(ContactPair::new(
            "CP1",
            SurfaceSetRef::new(0, 0),
            SurfaceSetRef::new(0, 1),
            ContactType::Tied,
        ));

        let contacts = resolve_contact_pairs(&model, Some(0), false).unwrap();
        let text = build_msh(&model.meshes[0], &contacts);

        assert!(text.contains("!CONTACT PAIR, NAME=CP1, TYPE=SURF-SURF\n SLAVE,MASTER\n"));
    }

    #[test]
    fn prefixes_contact_surface_groups_in_assembly_export() {
        let mut model = FemModel::single_mesh("gear", FemMesh::demo_hex8());
        model.add_mesh("shaft", FemMesh::demo_hex8());
        add_surface(&mut model.meshes[0], "TEETH", 1);
        add_surface(&mut model.meshes[1], "OUTER", 2);
        model.contacts.push(ContactPair::new(
            "GEAR_SHAFT",
            SurfaceSetRef::new(0, 0),
            SurfaceSetRef::new(1, 0),
            ContactType::Frictionless,
        ));

        let contacts = resolve_contact_pairs(&model, None, true).unwrap();

        assert_eq!(
            contacts,
            vec![ExportContactPair {
                name: "GEAR_SHAFT".into(),
                slave_group: "SHAFT_OUTER".into(),
                master_group: "GEAR_TEETH".into(),
            }]
        );
    }

    #[test]
    fn preserves_every_documented_frontistr_element_code() {
        let mesh = crate::parse_mesh_str(include_str!("../tests/fixtures/element_library.msh"))
            .unwrap();
        let text = build_msh(&mesh, &[]);
        let reparsed = crate::parse_mesh_str(&text).unwrap();
        let original_types: Vec<_> = mesh
            .elements
            .iter()
            .map(|element| element.element_type.clone())
            .collect();
        let reparsed_types: Vec<_> = reparsed
            .elements
            .iter()
            .map(|element| element.element_type.clone())
            .collect();

        assert_eq!(reparsed_types, original_types);

        for code in [
            "111", "112", "231", "232", "241", "242", "301", "341", "342", "351", "352",
            "361", "362", "511", "541", "542", "611", "641", "731", "732", "741", "743",
            "761", "781",
        ] {
            assert!(
                text.contains(&format!("!ELEMENT,TYPE={code}")),
                "missing HECMW element block {code}"
            );
        }
    }
}
