//! Writer for the HECMW mesh file format (`.msh`).
//!
//! The HECMW `.msh` format is what FrontISTR expects as its mesh input,
//! specified in `hecmw_ctrl.dat`. This writer produces the subset of keywords
//! that every non-trivial FrontISTR analysis needs:
//!
//!   `!HEADER`, `!NODE`, `!ELEMENT` (one block per element type),
//!   `!NGROUP`, `!EGROUP`, `!SGROUP`, `!END`
//!
//! Coordinates are written in full `f64`-formatted `f32` values (6 decimal
//! places) so precision is not lost in a read-modify-write round-trip even
//! though `FemNode::position` is `Vec3` (f32).
//!
//! # Multi-part assembly export
//!
//! HECMW's `.msh` format has no native concept of "multiple meshes in one
//! file" the way an assembly might — everything is one flat
//! node/element/group space. So when a [`FemModel`] has more than one part
//! (built via "+ Import"), [`write_msh_file`] flattens them into a single
//! mesh by re-numbering every part's node and element IDs into disjoint
//! ranges (offsetting by the running totals of all earlier parts) and
//! prefixing every group name with the part name (`PART2_EGRP1`) so that
//! identically-named groups from different source files don't collide.
//! Contact pairs between parts are *not* exported here — contacts live in
//! the `.cnt` writer's domain, not the mesh writer's, and aren't part of
//! this change.

use std::fmt::Write as FmtWrite;
use std::io;
use std::path::Path;

use fem_core::{ElementId, ElementType, FemMesh, FemModel, NodeId};

// ─── public API ──────────────────────────────────────────────────────────────

/// Writes the first mesh of `model` to `path` in HECMW `.msh` format.
///
/// Returns the number of nodes and elements written on success, for the
/// caller to surface in the status bar.
///
/// For models with a single mesh, this is equivalent to (and a thin
/// wrapper over) [`write_msh_assembly`] — kept as a separate name because
/// "write the mesh" reads more naturally than "write the assembly" for the
/// overwhelmingly common single-part case, and existing callers don't need
/// to change.
pub fn write_msh_file(
    path: impl AsRef<Path>,
    model: &FemModel,
    mesh_index: usize,
) -> io::Result<(usize, usize)> {
    let mesh = model.meshes.get(mesh_index).ok_or_else(|| {
        io::Error::new(io::ErrorKind::InvalidInput, "mesh index out of range")
    })?;

    let text = build_msh(mesh, "");
    std::fs::write(path, text.as_bytes())?;

    Ok((mesh.nodes.len(), mesh.elements.len()))
}

/// Writes **every** mesh in `model` to `path` as one flattened HECMW
/// `.msh`, renumbering node/element IDs into disjoint ranges and prefixing
/// group names by part so multi-part assemblies (built via "+ Import")
/// export correctly instead of silently dropping every part after the
/// first.
///
/// Returns `(total_nodes, total_elements, part_count)`.
pub fn write_msh_assembly(
    path: impl AsRef<Path>,
    model: &FemModel,
) -> io::Result<(usize, usize, usize)> {
    if model.meshes.len() <= 1 {
        // Single-part fast path — no renumbering or prefixing needed.
        let (n, e) = write_msh_file(&path, model, 0)?;
        return Ok((n, e, model.meshes.len()));
    }

    let mut combined = String::with_capacity(1024 * 64 * model.meshes.len());
    writeln!(combined, "!HEADER").unwrap();
    writeln!(combined, " Generated by bevyistr (assembly, {} parts)", model.meshes.len()).unwrap();

    // First pass: compute per-part ID offsets so every part's node/element
    // IDs land in a disjoint range in the combined file.
    let mut node_offset: u32 = 0;
    let mut elem_offset: u32 = 0;
    let mut offsets: Vec<(u32, u32)> = Vec::with_capacity(model.meshes.len());
    for mesh in &model.meshes {
        offsets.push((node_offset, elem_offset));
        node_offset += mesh.nodes.iter().map(|n| n.id.0).max().unwrap_or(0) + 1;
        elem_offset += mesh.elements.iter().map(|e| e.id.0).max().unwrap_or(0) + 1;
    }

    // ── NODE (all parts) ──
    writeln!(combined, "!NODE").unwrap();
    for (mesh, &(noff, _)) in model.meshes.iter().zip(&offsets) {
        for node in &mesh.nodes {
            writeln!(
                combined, " {},{:.6},{:.6},{:.6}",
                node.id.0 + noff, node.position.x, node.position.y, node.position.z,
            ).unwrap();
        }
    }

    // ── ELEMENT (all parts, grouped by type across all parts) ──
    let mut type_codes_seen: Vec<&str> = Vec::new();
    for mesh in &model.meshes {
        for el in &mesh.elements {
            if let Some(code) = element_type_code(&el.element_type) {
                if !type_codes_seen.contains(&code) { type_codes_seen.push(code); }
            }
        }
    }
    for code in &type_codes_seen {
        writeln!(combined, "!ELEMENT,TYPE={code}").unwrap();
        for (mesh, &(noff, eoff)) in model.meshes.iter().zip(&offsets) {
            for el in mesh.elements.iter().filter(|e| element_type_code(&e.element_type) == Some(code)) {
                let node_list: Vec<String> = el.nodes.iter().map(|n| (n.0 + noff).to_string()).collect();
                writeln!(combined, " {},{}", el.id.0 + eoff, node_list.join(",")).unwrap();
            }
        }
    }

    // ── NGROUP / EGROUP / SGROUP (prefixed by part name to avoid collisions) ──
    for (part_index, (mesh, &(noff, eoff))) in model.meshes.iter().zip(&offsets).enumerate() {
        let part_name = model.parts.iter()
            .find(|p| p.mesh_index == part_index)
            .map(|p| sanitize_group_prefix(&p.name))
            .unwrap_or_else(|| format!("PART{}", part_index + 1));

        for nset in &mesh.node_sets {
            writeln!(combined, "!NGROUP,NGRP={part_name}_{}", nset.name).unwrap();
            write_id_list(&mut combined, nset.nodes.iter().map(|n| n.0 + noff));
        }
        for eset in &mesh.element_sets {
            writeln!(combined, "!EGROUP,EGRP={part_name}_{}", eset.name).unwrap();
            write_id_list(&mut combined, eset.elements.iter().map(|e| e.0 + eoff));
        }
        for sset in &mesh.surface_sets {
            writeln!(combined, "!SGROUP,SGRP={part_name}_{}", sset.name).unwrap();
            for surf in &sset.surfaces {
                writeln!(combined, " {},{}", surf.element.0 + eoff, surf.local_face.0).unwrap();
            }
        }
    }

    writeln!(combined, "!END").unwrap();
    std::fs::write(path, combined.as_bytes())?;

    let total_nodes:    usize = model.meshes.iter().map(|m| m.nodes.len()).sum();
    let total_elements: usize = model.meshes.iter().map(|m| m.elements.len()).sum();

    Ok((total_nodes, total_elements, model.meshes.len()))
}

/// Builds the global node/element ID remap a multi-part export would use,
/// without writing anything — exposed mainly for tests and for the `.cnt`
/// writer, which needs the *same* offsets to remap boundary
/// conditions/loads/sections that reference node or element IDs from a
/// specific part's original numbering.
pub fn assembly_id_offsets(model: &FemModel) -> Vec<(u32, u32)> {
    let mut node_offset: u32 = 0;
    let mut elem_offset: u32 = 0;
    let mut offsets = Vec::with_capacity(model.meshes.len());
    for mesh in &model.meshes {
        offsets.push((node_offset, elem_offset));
        node_offset += mesh.nodes.iter().map(|n| n.id.0).max().unwrap_or(0) + 1;
        elem_offset += mesh.elements.iter().map(|e| e.id.0).max().unwrap_or(0) + 1;
    }
    offsets
}

/// Remaps a `(mesh_index, NodeId)` pair to its assembly-wide [`NodeId`]
/// using the offsets from [`assembly_id_offsets`].
pub fn remap_node(offsets: &[(u32, u32)], mesh_index: usize, id: NodeId) -> NodeId {
    let (noff, _) = offsets.get(mesh_index).copied().unwrap_or((0, 0));
    NodeId(id.0 + noff)
}

/// Remaps a `(mesh_index, ElementId)` pair to its assembly-wide
/// [`ElementId`] using the offsets from [`assembly_id_offsets`].
pub fn remap_element(offsets: &[(u32, u32)], mesh_index: usize, id: ElementId) -> ElementId {
    let (_, eoff) = offsets.get(mesh_index).copied().unwrap_or((0, 0));
    ElementId(id.0 + eoff)
}

// ─── implementation ──────────────────────────────────────────────────────────

/// Strips characters that would be ambiguous or illegal in a HECMW group
/// name (commas, whitespace) from a part's display name when using it as a
/// group-name prefix.
fn sanitize_group_prefix(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect::<String>()
        .trim_end_matches(".msh")
        .to_string()
        .to_ascii_uppercase()
}

fn write_id_list(out: &mut String, ids: impl Iterator<Item = u32>) {
    let mut col = 0;
    let ids: Vec<u32> = ids.collect();
    for (i, id) in ids.iter().enumerate() {
        if col == 0 {
            write!(out, " {id}").unwrap();
        } else {
            write!(out, ",{id}").unwrap();
        }
        col += 1;
        if col == 10 || i + 1 == ids.len() {
            writeln!(out).unwrap();
            col = 0;
        }
    }
}

fn element_type_code(et: &ElementType) -> Option<&'static str> {
    match et {
        ElementType::Rod2    => Some("111"),
        ElementType::Tri3    => Some("231"),
        ElementType::Tri6    => Some("232"),
        ElementType::Quad4   => Some("241"),
        ElementType::Quad8   => Some("242"),
        ElementType::Tet4    => Some("341"),
        ElementType::Tet10   => Some("342"),
        ElementType::Prism6  => Some("351"),
        ElementType::Prism15 => Some("352"),
        ElementType::Hex8    => Some("361"),
        ElementType::Hex20   => Some("362"),
        ElementType::Beam611 => Some("611"),
        ElementType::Beam641 => Some("641"),
        ElementType::Unsupported(_) => None,
    }
}

fn build_msh(mesh: &FemMesh, _group_prefix: &str) -> String {
    let mut out = String::with_capacity(1024 * 64);

    // ── HEADER ──
    writeln!(out, "!HEADER").unwrap();
    writeln!(out, " Generated by bevyistr").unwrap();

    // ── NODE ──
    writeln!(out, "!NODE").unwrap();
    for node in &mesh.nodes {
        writeln!(
            out,
            " {},{:.6},{:.6},{:.6}",
            node.id.0,
            node.position.x,
            node.position.y,
            node.position.z,
        ).unwrap();
    }

    // ── ELEMENT — one !ELEMENT block per unique element type ──
    let mut type_codes_seen: Vec<&str> = Vec::new();
    for el in &mesh.elements {
        if let Some(code) = element_type_code(&el.element_type) {
            if !type_codes_seen.contains(&code) {
                type_codes_seen.push(code);
            }
        }
    }

    for code in &type_codes_seen {
        writeln!(out, "!ELEMENT,TYPE={code}").unwrap();

        for el in mesh.elements.iter().filter(|e| element_type_code(&e.element_type) == Some(code)) {
            let node_list: Vec<String> = el.nodes.iter().map(|n| n.0.to_string()).collect();
            writeln!(out, " {},{}", el.id.0, node_list.join(",")).unwrap();
        }
    }

    // ── NGROUP ──
    for nset in &mesh.node_sets {
        writeln!(out, "!NGROUP,NGRP={}", nset.name).unwrap();
        write_id_list(&mut out, nset.nodes.iter().map(|n| n.0));
    }

    // ── EGROUP ──
    for eset in &mesh.element_sets {
        writeln!(out, "!EGROUP,EGRP={}", eset.name).unwrap();
        write_id_list(&mut out, eset.elements.iter().map(|e| e.0));
    }

    // ── SGROUP (surface groups) ──
    for sset in &mesh.surface_sets {
        writeln!(out, "!SGROUP,SGRP={}", sset.name).unwrap();
        for surf in &sset.surfaces {
            writeln!(out, " {},{}", surf.element.0, surf.local_face.0).unwrap();
        }
    }

    writeln!(out, "!END").unwrap();

    out
}

