[package]
name = "ui"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.19"
camera = { path = "../camera" }
fem_core = { path = "../fem_core" }
gmsh = { path = "../gmsh" }
hecmw = { path = "../hecmw" }
interaction = { path = "../interaction" }
picking = { path = "../picking" }
rfd = "0.15"
selection = { path = "../selection" }
visualization = { path = "../visualization" }
